### ISSUE TITLE
setup SOLVCON project and prepare the PPA for the debian packages.

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#119]
Originally reported by: **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**

---
- SOLVCON on Launchpad https://launchpad.net/solvcon

action items:
- ~~preliminary packaging 0.1.3 rc~~
- ~~update the packaging for 0.1.4~~
- ~~Choose the correct license when registering a project on Launchpad~~
- create three PPA, one for release, one for testing and the other for dev
- update the packaging for 0.2

---
- Bitbucket: https://bitbucket.org/solvcon/solvcon/issue/119

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

add tasks to maintain the debian packages

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

Ref issue #119 include necessary import files and Ubuntu/debian python deployed path. Put test/data to /usr/lib/python2.7/dist-packages/share/solvcon/test

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

Ref issue #119 first initialize debian files

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

Ref issue #119 remove useless automatically generated debian files

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

Ref issue #119 add real copiright information in the copyright file

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

to package 0.1.4 we need to tweak source tree a little bit, see:

https://bitbucket.org/solvcon/solvcon/pull-request/63/issue-119-first-and-preliminary-debianize/diff

so I don't think it is worthy to write a specific rule of debian files for 0.1.4 and to abandon the patch in the next release. Let's mark "update the packaging for 0.1.4" as done.

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Ref issue #119 add comments to remind why to use such path in details

**Comment by yungyuc** [comment]
_Original comment by_ **Taihsiang Ho (BitBucket: [tai271828](http://bitbucket.org/tai271828), GitHub: [tai271828](http://github.com/tai271828))**:

---

patch 15w31-scons-clean-headers.patch

rm the header files as well when applying scons --clean, so debian rules could be more concise.

**Comment by yungyuc** [comment]
_Original comment by_ **Yung-Yu Chen (BitBucket: [yungyuc](http://bitbucket.org/yungyuc), GitHub: [yungyuc](http://github.com/yungyuc))**:

---

Ref issue #119 rm the header files as well when applying scons --clean so debian rules could be concise

**Comment by yungyuc** [comment]
@tai271828 is this still active?  I found this after opened #132.  Should we have two issues or should we merge them?

**Comment by tai271828** [comment]
The first thing came to my mind is having two issues because PPA is a builder and package sharing repository for Ubuntu/Debian system. I think this issue is different from #132.

Please let me study a bit further and back to comment this question, thanks.

**Comment by yungyuc** [comment]
@tai271828 what is your plan with this ticket?  The C++ porting and/or development for the CESE method is still in progress.  At this point, I don't have a schedule for the next release (0.1.4+) yet.

**Comment by yungyuc** [comment]
@tai271828 if you aren't interested in this ticket anymore, I'd like to close it.

**Comment by tai271828** [comment]
No, please close it. This is a "good to have" task. We don't have urgent need to complete this task. I am focusing on the other stuff now. Thus let's close it and re-open it anytime if we want.

**Comment by yungyuc** [comment]
Close for we don't invest time for PPA at this point.
