### ISSUE TITLE
Debian files should update to use github

### ISSUE THREAD

**Issue by yungyuc** [solvcon/pastsolvcon#132]
In $root/debian/, control and copyright files have bitbucket hardcoded.  The strings should be updated to use github.

**Comment by yungyuc** [comment]
@tai271828 I agree your [comment](https://github.com/solvcon/solvcon/issues/119#issuecomment-163139480) in #119.  This debian file issue should be separate from the PPA issue.

**Comment by yungyuc** [comment]
@tai271828 do you still want to maintain the debian packaging?

**Comment by tai271828** [comment]
No, please close it. This is a "good to have" task. We don't have urgent need to complete this task. I am focusing on the other stuff now. Thus let's close it and re-open it anytime if we want.

**Comment by yungyuc** [comment]
Close for we don't invest time for Debian packaging at this point.
