### ISSUE TITLE
build a solid 1D Sod tube test case

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#138]
for study etc.

**Comment by yuhow** [comment]
I update my CESE solver and comparator. They can be found in 'solvcon/sandbox/my_sod_shock_stube_solver'.

**Comment by tai271828** [comment]
I created a python package to provide 1D analytic solutions, [shocktube1dcalc](https://pypi.org/project/shocktube1dcalc/).

**Comment by yungyuc** [comment]
> I created a python package to provide 1D analytic solutions, [shocktube1dcalc](https://pypi.org/project/shocktube1dcalc/).

I like the idea very much!

**Comment by tai271828** [comment]
@yungyuc according to our [previous discussion](https://discord.com/channels/730297880140578906/730393342818648204/811382408401518643) regarding to a new repository for shock tube problem, I think it is time to create the repository. Would you please do that?

I have released [shocktube1dcalc 1.0.0](https://pypi.org/project/shocktube1dcalc/), which not only offers analytic solutions, but also solutions based on CESE. People could invoke [contrib/compare-1d-by-animation.py](https://github.com/tai271828/shocktube1dcalc/blob/main/contrib/compare-1d-by-animation.py) to get [the animation of CESE vs. analytic solution](https://drive.google.com/file/d/1ARycROx-kLW73PPrzj37nVd_kUnzVAer/view?usp=sharing). You may also see the screenshot of the animation below (green: analytic, blue: CESE). The result looks good to me.

If the result looks good to you as well, I would say, In conclusion:
1.  [shocktube1dcalc](https://pypi.org/project/shocktube1dcalc/) is ready to be a sub-project of SOLVCON. I will migrate [the upstream codebase](https://github.com/tai271828/shocktube1dcalc/) once the sub-project is created.
2. Close this issue. We will trace any 1D topics in the sub-project.



![Selection_158](https://user-images.githubusercontent.com/3217432/111044690-64e35b00-844a-11eb-854e-ffece67b4403.png)

**Comment by yungyuc** [comment]
LGTM, @tai271828 !  Is https://github.com/solvcon/shocktube1dcalc what you want?

**Comment by tai271828** [comment]
> LGTM, @tai271828 ! Is https://github.com/solvcon/shocktube1dcalc what you want?

@yungyuc yes! The repository looks good to me. I will continue the up-coming tasks. Thank you for your help.

**Comment by tai271828** [comment]
> 1. [shocktube1dcalc](https://pypi.org/project/shocktube1dcalc/) is ready to be a sub-project of SOLVCON. I will migrate [the upstream codebase](https://github.com/tai271828/shocktube1dcalc/) once the sub-project is created.
> 2. Close this issue. We will trace any 1D topics in the sub-project.

All done. For now we have a sub-project `solvcon/shocktube1dcalc`. I also did some house cleaning of SOLVCON with this pull request https://github.com/solvcon/solvcon/pull/234 . Close this issue.
