### ISSUE TITLE
system-wide installation did not deploy external build extensions correctly

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#145]
# Description:

After #143 and #144 were fixed, I run unit tests:
1. there were many failed items
2. failed message is different from the environment prepared by

(system-wide)

```
python setup.py install
```

and

(locally)

```
python setup.py build_ext --inplace
```
# Steps to reproduce this issue:
1. fetch the latest source code (make sure it is merged the branch for #143 and #144)
2. build the code system-wide or locally
3. run unit tests by

```
python -c 'import solvcon as sc; sc.test()'
```
# Expected result

only unit tests related to EC2 failed
# Actual result
## failure message of system-wide build[1]

```
Traceback (most recent call last):
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/dependency.py", line 80, in import_module_may_fail
    mod = importlib.import_module(modname, package)
  File "/home/tai271828/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'solvcon.mesh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/dependency.py", line 52, in resolve_name
    name = importlib._resolve_name(name[level:], package, level)
AttributeError: module 'importlib' has no attribute '_resolve_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/__init__.py", line 91, in <module>
    from .block import Block
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/block.py", line 49, in <module>
    from . import boundcond
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/boundcond.py", line 47, in <module>
    dependency.import_module_may_fail('.mesh')
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/dependency.py", line 87, in import_module_may_fail
    name = resolve_name(modname, package)
  File "/home/tai271828/work-my-projs/solvcon/test-160302-systemwide/solvcon/dependency.py", line 54, in resolve_name
    name = importlib.util.resolve_name(name, package)
AttributeError: module 'importlib' has no attribute 'util'

```
## failure message of local build:

full log
http://paste.ubuntu.com/15265010/

please note there is something like[2]:

```
OSError: /tmp/tmpaa95o1r5/gmsh.msh not produced by gmsh command line, stdout:
b"gmsh: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by gmsh)\n"
```
# misc:

[1] this looks like python 2 and 3 compatibility issue and is expected to be fixed already?
[2] this might be relevant to OS type. got to figure out the glib used by my host os (Ubuntu trusty)

**Comment by yungyuc** [comment]
See https://github.com/solvcon/solvcon/blob/f19670b16fe99103833e680131bfbe67a2db54c7/solvcon/dependency.py#L51 .  In Python 2 there is importlib._resolve_name(), but in Python 3 it's importlib.util.resolve_name().  It's weird to see both failures at the same time.  Perhaps your Python installation is messed up?

**Comment by tai271828** [comment]
thanks for the comment. it is so clear. let me check.

**Comment by tai271828** [comment]
for system-wide build, please note the error message

```
ImportError: No module named 'solvcon.mesh'
```

so I noted there is no **mesh.cpython-35m-x86_64-linux-gnu.so** under **<source code>/solvcon**[1] so the program stopped.
That is, 
`python setup.py install`
did not build the mesh library?

[1] I did not find mesh*.so in my conda environment as well.

**Comment by yungyuc** [comment]
Try python setup.py build_ext --inplace and then install.  This is about distutil, which should be traced into.

**Comment by tai271828** [comment]
**setup.py build_ext --inplace** and then install (by **python setup.py install**)
could reproduce the 'GLIBCXX_3.4.20 not found' issue.

besides, on my system

```
└──╼ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

so it is a system-specific issue indeed.
Two solutions are expected:
1. use a new libstdc++.so - re-compile libstdc++.so with newer source or install newer libstdc++.so binary directly.
2. use system gmsh instead of the one conda provides (this issue was reported with gmsh provided by conda environment)

**Comment by tai271828** [comment]
by removing the gmsh provided by conda environment and using the gmsh provided by my system, the GLIBCXX issue went away. Here are the gmsh version I used and unit test result:

**gmsh version**
conda provides: 2.8.4
my Ubuntu Trusty uses: 2.8.3+dfsg-4ubuntu2

**unit test result:**

```
python -c 'import solvcon as sc; sc.test()'
.........................................................................................................................................SSS/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:324: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1.blk'>
  meta = bio.read_meta()
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:326: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1.blk'>
  blkl = bio.load()
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:342: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1.blk'>
  meta = bio.read_meta()
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:344: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1.blk'>
  blkl = bio.load()
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:361: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1.blk'>
  meta = bio.read_meta()
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:363: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1.blk'>
  blkl = bio.load()
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:379: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1.blk'>
  meta = bio.read_meta()
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:381: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1.blk'>
  blkl = bio.load()
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:300: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.7_bz2.blk'>
  'oblique_0.0.7_bz2.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:296: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.7_gz.blk'>
  'oblique_0.0.7_gz.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:292: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.7.blk'>
  'oblique_0.0.7.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:312: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.7_bz2.blk'>
  'sample_0.0.7_bz2.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:308: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.7_gz.blk'>
  'sample_0.0.7_gz.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:304: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.7.blk'>
  'sample_0.0.7.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:154: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1_bz2.blk'>
  'oblique_0.0.0.1_bz2.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:150: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1_gz.blk'>
  'oblique_0.0.0.1_gz.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:146: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1.blk'>
  'oblique_0.0.0.1.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:166: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1_bz2.blk'>
  'sample_0.0.0.1_bz2.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:162: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1_gz.blk'>
  'sample_0.0.0.1_gz.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:158: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1.blk'>
  'sample_0.0.0.1.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:223: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1_bz2.blk'>
  'oblique_0.0.1_bz2.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:219: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1_gz.blk'>
  'oblique_0.0.1_gz.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:215: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1.blk'>
  'oblique_0.0.1.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:235: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1_bz2.blk'>
  'sample_0.0.1_bz2.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:231: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1_gz.blk'>
  'sample_0.0.1_gz.blk', 'rb'))
./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:227: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1.blk'>
  'sample_0.0.1.blk', 'rb'))
................................................................................../home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:58: DeprecationWarning: Please use assertTrue instead.
  self.assert_((blk.fccls[exfcs,1] < 0).all())
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:63: DeprecationWarning: Please use assertTrue instead.
  self.assert_(icl in ecls)
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:65: DeprecationWarning: Please use assertTrue instead.
  self.assert_(icl in ocls)
../home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:24: DeprecationWarning: Please use assertTrue instead.
  '[Neutral (Example): 60 nodes, 116 elements, 1 groups, 2 bcs]')
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:26: DeprecationWarning: Please use assertTrue instead.
  '[Group #1(fluid): 116 elements]')
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:28: DeprecationWarning: Please use assertTrue instead.
  '[BC "element_side.1": 14 entries with 0 values]')
/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:30: DeprecationWarning: Please use assertTrue instead.
  '[BC "node.2": 16 entries with 0 values]')
.........
----------------------------------------------------------------------
Ran 254 tests in 5.045s

OK (SKIP=3)

```

**Comment by yungyuc** [comment]
There is a mismatch of test numbers between in-place built SOLVCON and installed SOLVCON.  I didn’t figure out why.  Before we fix it I suggest to run nose in-place (build SOLVCON using python setup.py build_ext --inplace).  The resource warnings should also be fixed.  I’ve cleaned all of them in the in-place version.

The conda Gmsh package was built on Debian stretch:

$ cat /etc/debian_version
8.3
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH

I think we should build it on a more solid host to avoid this problem.

> On Mar 4, 2016, at 12:39 AM, Taihsiang Ho <notifications@github.com> wrote:
> 
> by removing the gmsh provided by conda environment and using the gmsh provided by my system, the GLIBCXX issue went away. Here are the gmsh version I used and unit test result:
> 
> gmsh version
> conda provides: 2.8.4
> my Ubuntu Trusty uses: 2.8.3+dfsg-4ubuntu2
> 
> unit test result:
> 
> python -c 'import solvcon as sc; sc.test()'
> .........................................................................................................................................SSS/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:324: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1.blk'>
>   meta = bio.read_meta()
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:326: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1.blk'>
>   blkl = bio.load()
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:342: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1.blk'>
>   meta = bio.read_meta()
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:344: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1.blk'>
>   blkl = bio.load()
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:361: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1.blk'>
>   meta = bio.read_meta()
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:363: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1.blk'>
>   blkl = bio.load()
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:379: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1.blk'>
>   meta = bio.read_meta()
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:381: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1.blk'>
>   blkl = bio.load()
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:300: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.7_bz2.blk'>
>   'oblique_0.0.7_bz2.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:296: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.7_gz.blk'>
>   'oblique_0.0.7_gz.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:292: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.7.blk'>
>   'oblique_0.0.7.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:312: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.7_bz2.blk'>
>   'sample_0.0.7_bz2.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:308: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.7_gz.blk'>
>   'sample_0.0.7_gz.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:304: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.7.blk'>
>   'sample_0.0.7.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:154: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1_bz2.blk'>
>   'oblique_0.0.0.1_bz2.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:150: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1_gz.blk'>
>   'oblique_0.0.0.1_gz.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:146: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.0.1.blk'>
>   'oblique_0.0.0.1.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:166: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1_bz2.blk'>
>   'sample_0.0.0.1_bz2.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:162: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1_gz.blk'>
>   'sample_0.0.0.1_gz.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:158: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.0.1.blk'>
>   'sample_0.0.0.1.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:223: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1_bz2.blk'>
>   'oblique_0.0.1_bz2.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:219: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1_gz.blk'>
>   'oblique_0.0.1_gz.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:215: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/oblique_0.0.1.blk'>
>   'oblique_0.0.1.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:235: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1_bz2.blk'>
>   'sample_0.0.1_bz2.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:231: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1_gz.blk'>
>   'sample_0.0.1_gz.blk', 'rb'))
> ./home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_block.py:227: ResourceWarning: unclosed file <_io.BufferedReader name='/home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/test/data/sample_0.0.1.blk'>
>   'sample_0.0.1.blk', 'rb'))
> ................................................................................../home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:58: DeprecationWarning: Please use assertTrue instead.
>   self.assert_((blk.fccls[exfcs,1] < 0).all())
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:63: DeprecationWarning: Please use assertTrue instead.
>   self.assert_(icl in ecls)
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:65: DeprecationWarning: Please use assertTrue instead.
>   self.assert_(icl in ocls)
> ../home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:24: DeprecationWarning: Please use assertTrue instead.
>   '[Neutral (Example): 60 nodes, 116 elements, 1 groups, 2 bcs]')
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:26: DeprecationWarning: Please use assertTrue instead.
>   '[Group #1(fluid): 116 elements]')
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:28: DeprecationWarning: Please use assertTrue instead.
>   '[BC "element_side.1": 14 entries with 0 values]')
> /home/tai271828/work-my-projects/solvcon/solvcon.160303.build.test/solvcon/io/tests/test_neutral.py:30: DeprecationWarning: Please use assertTrue instead.
>   '[BC "node.2": 16 entries with 0 values]')
> .........
> ----------------------------------------------------------------------
> Ran 254 tests in 5.045s
> 
> OK (SKIP=3)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/solvcon/solvcon/issues/145#issuecomment-191844410>.
> 

--
Yung-Yu Chen
http://yyc.solvcon.net/
+886 (99) 129 4763

**Comment by yungyuc** [comment]
There is a mismatch of test numbers between in-place built SOLVCON and installed SOLVCON.  I didn’t figure out why.  Before we fix it I suggest to run nose in-place (build SOLVCON using python setup.py build_ext --inplace).  The resource warnings should also be fixed.  I’ve cleaned all of them in the in-place version.

The conda Gmsh package was built on Debian stretch:

```
$ cat /etc/debian_version
8.3
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

I think we should build it on a more solid host to avoid this problem.

**Comment by tai271828** [comment]
For test number issue, I filed #146 to trace the issue. Please update relevant study on #146.

**Comment by tai271828** [comment]
This issue has not been touched for a while and things may change. I try to reproduce this issue with the latest SOLVCON and the inconsistency between system-wide and local installation is still there.

The ``nosetests --with-doctest`` result of system-wide installation

```
Ran 242 tests in 2.435s

FAILED (SKIP=3, errors=100, failures=32)

```

And The ``nosetests --with-doctest`` result of local installation

```
.................................................................................................................................................................................................................................................................................................................................................................SSS
----------------------------------------------------------------------
Ran 356 tests in 3.903s

OK (SKIP=3)

```
The build was done on Ubuntu 16.04.

**Comment by yungyuc** [comment]
The missing extension module in installation is fixed with https://github.com/solvcon/solvcon/commit/ed8c95bcdf31c986c0b1239f6db21784d40ced16 .  The difference in number of tests is intentional, as explained in issue #146 .

The code is in master branch.  I am closing this issue.  If there's any problem please reopen.
