### ISSUE TITLE
build gmsh-compatible glibc

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#147]
gmsh built on Debian stretch may be not consistent with glibc library on other systems.
We may need to build SOLVCON-specific glibc so it could run on different systems smoothly.

Please refer to this comment of #145.
https://github.com/solvcon/solvcon/issues/145#issuecomment-192033672

**Comment by yungyuc** [comment]
@tai271828, we'd need to do something with this and #145, #146.

**Comment by tai271828** [comment]
We have not touched this issue for a while and Debian stretch has officially released on June 17th 2017. I tried to reproduce the issue today by ``python setup.py build_ext --inplace``, and the result looks good now[1]. The issue could not be reproduced anymore.

The reason that we could not reproduce this issue may be:
- Debian stretch bumps its glibc
- gmsh version bumps

I didn't look into the details. However I suppose that it should be Debian stretch changed before officially releasing. 


[1] 

```
(root) ubuntu@debian:~/solvcon$ nosetests --with-doctest
.................................................................................................................................................................................................................................................................................................................................................................SSS
----------------------------------------------------------------------
Ran 356 tests in 4.569s

OK (SKIP=3)
(root) ubuntu@debian:~/solvcon$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
(root) ubuntu@debian:~/solvcon$ uname -a
Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

**Comment by yungyuc** [comment]
Sounds like this issue may be closed.  Please reopen if otherwise.

**Comment by tai271828** [comment]
Checked the stdc++ lib and stretch did bump its version[1]. We could close this issue.


[1] It is now GLIBCXX_3.4.22 instead of GLIBCXX_3.4.20 reported in https://github.com/solvcon/solvcon/issues/145#issuecomment-192033672

```

(root) ubuntu@debian:~/solvcon$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
(root) ubuntu@debian:~/solvcon$ uname -a
Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
(root) ubuntu@debian:~/solvcon$ man strings 
(root) ubuntu@debian:~/solvcon$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_DEBUG_MESSAGE_LENGTH
(root) ubuntu@debian:~/solvcon$ 

```

**Comment by yungyuc** [comment]
This is already closed.

**Comment by tai271828** [comment]
Yes it is closed. I wanted to add more information for reference in the future to make it more completed.
