### ISSUE TITLE
Build error on Ubuntu Bionic

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#226]
Unfortunately, SOLVCON can't be built on Ubuntu Bionic. We will want to fix this before Xenial reaches its end of life (2021). We have one remaining year : ) The corresponding error message is

```
creating build/temp.linux-x86_64-3.6/solvcon/src
compile options: '-Isolvcon -Isolvcon -I/home/travis/build/tai271828/solvcon/build/env/install/lib/python3.6/site-packages/numpy/core/include -I/home/travis/build/tai271828/solvcon/build/env/install/include/python3.6m -c'
extra options: '-Werror -Wno-cpp -Wno-unused-function'
gcc: solvcon/mesh.c
gcc: solvcon/src/sc_mesh_calc_metric.c
solvcon/src/sc_mesh_calc_metric.c: In function ‘sc_mesh_calc_metric’:
solvcon/src/sc_mesh_calc_metric.c:370:38: error: ‘ndstf[3]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                         pfcnds[jt+1] = ndstf[jt];
                         ~~~~~~~~~~~~~^~~~~~~~~~~
cc1: all warnings being treated as errors
gcc: solvcon/src/sc_mesh_extract_faces_from_cells.c
gcc: solvcon/src/sc_mesh_build_rcells.c
gcc: solvcon/src/sc_mesh_build_csr.c
gcc: solvcon/src/sc_mesh_build_ghost.c
error: Command "gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isolvcon -Isolvcon -I/home/travis/build/tai271828/solvcon/build/env/install/lib/python3.6/site-packages/numpy/core/include -I/home/travis/build/tai271828/solvcon/build/env/install/include/python3.6m -c solvcon/src/sc_mesh_calc_metric.c -o build/temp.linux-x86_64-3.6/solvcon/src/sc_mesh_calc_metric.o -MMD -MF build/temp.linux-x86_64-3.6/solvcon/src/sc_mesh_calc_metric.o.d -Werror -Wno-cpp -Wno-unused-function" failed with exit status 1
Makefile:73: recipe for target 'legacy' failed
make[1]: *** [legacy] Error 1
make[1]: Leaving directory '/home/travis/build/tai271828/solvcon/dist/SOLVCON-0.1.4+'
```

# Steps to Reproduce

Modify your `.travis.yaml` from `xenial` to be `bionic` and you will get the error.

**Comment by tai271828** [comment]
The possible root cause might be the version difference between Xenial (gcc 5) and Bionic (gcc 7).

**Comment by yungyuc** [comment]
That is a false alarm of GCC 7.  In https://github.com/solvcon/solvcon/blob/master/solvcon/src/sc_mesh_calc_metric.c#L367 ndstf is initialized (quote the full block):

```c
                    nnd = pfcnds[0];
                    for (jt=0; jt<nnd; jt++) {
                        ndstf[jt] = pfcnds[nnd-jt]; // line 367
                    };
                    for (jt=0; jt<nnd; jt++) {
                        pfcnds[jt+1] = ndstf[jt]; // line 370
                    };
                    for (idm=0; idm<msd->ndim; idm++) {
                        pfcnml[idm] = -pfcnml[idm];
                    };
```

We should silence GCC for that using [pragma](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html) (for the line) or [option](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Warning-Options.html) (for the file).

**Comment by tai271828** [comment]
Is `nnd` always equal to `FCMND`?

At https://github.com/solvcon/solvcon/blob/master/solvcon/src/sc_mesh_calc_metric.c#L56 , `nnd` will fully initialize `ndstf[FCMND]` every time only if `nnd` is always equal to `FCMND`.

**Comment by yungyuc** [comment]
`nnd` may be equal to or smaller than `FCMND`.  `jt` must be smaller than `nnd`, so `ndstf[jt]` at line 370 always uses the value initialized at line 367.

I think lines 367 and 370 can be combined into one, and `ndstf[jt]` becomes unnecessary.  But that file is very old legacy code, which I do not plan to use anymore.  I don't see much value updating it.

**Comment by tai271828** [comment]
I see. If it is so legacy and won't be used at all, it is acceptable to silent the code build warning.

**Comment by yungyuc** [comment]
Yes.  I think you can update https://github.com/solvcon/solvcon/pull/227 to deprecate the warning instead.
