### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#238]
A bug tracker for people to follow up the initiative of this pull request draft[1] easily by searhing Issues.

[1] https://github.com/solvcon/solvcon/pull/235#issuecomment-828477913

**Comment by tai271828** [comment]
This CI run by a draft codebase shows SOLVCON is built and run with python 3.8. https://github.com/tai271828/solvcon/actions/runs/1088314972

Unfortunately, the test for macOS failed. I have not figured out why. Need to have a closer look.

**Comment by yungyuc** [comment]
The numpy binary suggests to use AVX512, but it does not build on the CI machine: https://github.com/tai271828/solvcon/runs/3215888293?check_suite_focus=true#step:8:1048

**Comment by yungyuc** [comment]
I tested locally with Python 3.7 and self-built numpy and it passed, but I don't know when I will have time to build with newer Python.

**Comment by tai271828** [comment]
> I tested locally with Python 3.7 and self-built numpy and it passed, but I don't know when I will have time to build with newer Python.

Uha, this is indeed informative. Let me try to include self-built numpy in the process as well. It's really good to know Python 3.7 works.

**Comment by tai271828** [comment]
Current status: it is ready to support python 3.8 with Ubuntu, but not macOS. Running SOLVCON with python 3.8 of devenv and macOS is currently blocked by https://github.com/solvcon/devenv/issues/83

**Comment by tai271828** [comment]
Fixed. Now it's at the stage of SOVLCON build error macOS https://github.com/tai271828/solvcon/runs/3580950845?check_suite_focus=true#step:9:1176 . We moved forward \o/

My quick skim shows it may be libc compatibility. @yungyuc would you mind having a look?

> Current status: it is ready to support python 3.8 with Ubuntu, but not macOS. Running SOLVCON with python 3.8 of devenv and macOS is currently blocked by [solvcon/devenv#83](https://github.com/solvcon/devenv/issues/83)

**Comment by yungyuc** [comment]
@tai271828 at https://github.com/tai271828/solvcon/runs/3580950845?check_suite_focus=true#step:9:1106 , it seems a Cython module is not successfully built because of a deprecated declaration in Python:

```
creating build/temp.macosx-10.9-x86_64-3.8/solvcon/src
compile options: '-Isolvcon -Isolvcon -I/Users/runner/work/solvcon/solvcon/build/env/install/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.macosx-10.9-x86_64-3.8/numpy/distutils/include -I/Users/runner/work/solvcon/solvcon/build/env/install/include/python3.8 -c'
extra options: '-Werror -Wno-#warnings -Wno-unused-function -msse -msse2 -msse3'
gcc: solvcon/mesh.c
gcc: solvcon/src/sc_mesh_build_rcells.c
gcc: solvcon/src/sc_mesh_extract_faces_from_cells.c
gcc: solvcon/src/sc_mesh_build_ghost.c
solvcon/mesh.c:6620:3: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
  0, /*tp_print*/
  ^
```

**Comment by tai271828** [comment]
Next action:
Figure out why the python 3.8 running in Ubuntu did not complain the deprecated declaration.

**Comment by tai271828** [comment]
@yungyuc I will keep working on this issue. May you assign the issue to me? I did not manage to assign myself : (  (no permission?)

**Comment by tai271828** [comment]
Currently we are working on this known issue https://github.com/cython/cython/issues/3474

**Comment by yungyuc** [comment]
> @yungyuc I will keep working on this issue. May you assign the issue to me? I did not manage to assign myself : ( (no permission?)

I have changed the permission for you.  Could you check if you can change the settings?

**Comment by tai271828** [comment]
> > @yungyuc I will keep working on this issue. May you assign the issue to me? I did not manage to assign myself : ( (no permission?)
> 
> I have changed the permission for you. Could you check if you can change the settings?

Yes. I have assigned myself : D

btw I could now build cython for mac with devenv with a specific python interpreter. I believe I am on the way to close this bug... : )

**Comment by yungyuc** [comment]
> > > @yungyuc I will keep working on this issue. May you assign the issue to me? I did not manage to assign myself : ( (no permission?)
> > 
> > 
> > I have changed the permission for you. Could you check if you can change the settings?
> 
> Yes. I have assigned myself : D
> 
> btw I could now build cython for mac with devenv with a specific python interpreter. I believe I am on the way to close this bug... : )

On the way to success.  Sounds so good :)

**Comment by tai271828** [comment]
I passed the build for ubuntu and mac both! Two items needing to be nailed down:

1. figure out which compiler flag could be safely used and turned off the warning to cause failure. It is `-Wno-deprecated-declarations`.
2. Inject the flag in the right way.

Bullet 2 took me some time to figure out the whole CMake and setup.py building chain : )

I will do some house cleaning for my code base and make a pull request soon.

**Comment by tai271828** [comment]
The first step of the house cleaning https://github.com/solvcon/devenv/pull/86 I need to update the codebase of `devenv` because I would like to use `devenv` to build SOLVCON and make the approach a part of the CI.

**Comment by yungyuc** [comment]
> The first step of the house cleaning [solvcon/devenv#86](https://github.com/solvcon/devenv/pull/86) I need to update the codebase of `devenv` because I would like to use `devenv` to build SOLVCON and make the approach a part of the CI.

Using devenv to build is a big step!  Super!

**Comment by tai271828** [comment]
I created another `devenv` pull request to get `devenv` ready to support/resolve this issue. https://github.com/solvcon/devenv/pull/88

**Comment by tai271828** [comment]
The above PR is merged. Close this issue. \o/ (bye python 3.6)
