### ISSUE TITLE
Fully integrate devenv

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#242]
`devenv` is getting stable, and we have begun to use `devenv` to build `SOLVCON`. However, there are some packages still prepared by `conda`. This issue will track the progress for migrating the packages managed by `conda` to `devenv`.

The packages pending to migrate could be found here https://github.com/solvcon/devenv/commit/6220f6fb6dd275204122e125009a6f1a3e368e44

Related issue: https://github.com/solvcon/devenv/issues/87

**Comment by yungyuc** [comment]
The devenv step takes long time.  Perhaps it should not be run on every checkin but nightly.

**Comment by tai271828** [comment]
Please note both SOLVCON and `devenv` could now weekly build SOLVCON https://github.com/solvcon/solvcon/actions/runs/1454292239 https://github.com/solvcon/devenv/actions/runs/1482262328 with `devenv`. This task is completed. Close this issue.
