### ISSUE TITLE
Consolidate the CI code

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#250]
Some of CI code snippet could be consolidated and put them in somewhere like `contrib` so they could be re-used easier by projects like `devenv`.

**Comment by tai271828** [comment]
Since https://github.com/solvcon/devenv/issues/98 is resolved in `devenv` side but not CI of `SOLVCON`, it's good timing for us to integrate both sides (`devenv` and `solvcon`), so we can accomplish both bug fixing and consolidation of code without duplicate of effort.

**Comment by yungyuc** [comment]
I think the code building `solvcon` with `devenv` only needs to exist in one place but not both.  Consolidation is good.

**Comment by tai271828** [comment]
Landed https://github.com/solvcon/solvcon/pull/254 . If CI passed on this Friday and we can feel free to close this issue.

**Comment by tai271828** [comment]
Scheduled job passed.
