### ISSUE TITLE
Bump CI from Ubuntu 18.04 to 20.04

### ISSUE THREAD

**Issue by tai271828** [solvcon/pastsolvcon#251]

**Comment by tai271828** [comment]
Or we may run the CI on both distributions.

**Comment by yungyuc** [comment]
Running on both versions is fine, but I do not think it is necessary.  20.04 alone should suffice.

**Comment by tai271828** [comment]
Landed https://github.com/solvcon/solvcon/pull/254 . If CI passed on this Friday and we can feel free to close this issue.

**Comment by tai271828** [comment]
Scheduled job passed.
