### ISSUE TITLE
when i make install the project , "RuntimeWarning: libmarch not found; create a dummy",then it all goes wrong

### ISSUE THREAD

**Issue by zhdd80** [solvcon/pastsolvcon#258]
when i build the libmarch ,many errors bump out, it seems the file gtest-all.cc went wrong, so i replace another one in gtest original file. then i make install again ,it terminates at 26%, still shows  libmarch not found.
anyone knows what's goes wrong.

**Comment by yungyuc** [comment]
@zhdd80 Could you please post the relevant log for the build error?

`gtest-all.cc` belongs to Google-test and it is downloaded when building.

**Comment by yungyuc** [comment]
@zhdd80 if you do not provide more information about the issue or what you are trying to do, I would probably need to block you from the repository.  Your conversation style, which lacks meaningful interaction, looks very similar to a spamming bot.

If you are not a bot and are interested in the project, please behave like a real person.
